name: Check outdate pod and create issue

on: 
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  check-outdated-pods:
    runs-on: macos-latest
    name: Check outdate pods and create issue if it doesn't exist
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Check outdated pods and create issue
        id: check-outdated-pods-and-create-issue
        uses: rudderlabs/github-action-updated-pods-notifier@main
        with:
          outdated-pod-names: "OptimizelySDKiOS"
          directory: "Example"
          title: "fix: update Optimizely SDK to the latest version"
          assignee: "desusai7"
          labels: "outdatedPod"
          color: "FBCA04"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the github issue url
        if: steps.check-outdated-pods-and-create-issue.outputs.issue-url != ''
        run: echo "The Github issue url is ${{ steps.check-outdated-pods-and-create-issue.outputs.issue-url }}"
